### ISSUE TITLE
One shoot notification

### ISSUE THREAD

**Issue by josete89** [LISNR/LNRSimpleNotifications#7]
Hello!

Exists any way for show a different notification from sharedInstace?

I have this code :

let notification = LNRSimpleNotifications()
        
        notification.notificationsPosition = LNRNotificationPosition.Top
        notification.notificationsBackgroundColor = UIColor.blueColor()
        notification.notificationsTitleTextColor = UIColor.whiteColor()
        notification.notificationsBodyTextColor = UIColor.whiteColor()
        
        notification.showNotification("Guardada correctamente", body: nil, callback: nil)

Show a notification and crashes!

**Comment by Jon-Schneider** [comment]
Hey josete89, I just made an update to the pod, version 0.3.0. It's pretty substantial - rather than using a singleton to handle notifications, you now create and retain an instance of LNRNotificationManager (which is the new name for the LNRSimpleNotifications class). This allows you to have multiple LNRNotificationManagers within your project, each with a separate theme, and your crash (which was caused by trying to use an new instnace of the LNRSimpleNotifications, which was meant to be used as a singleton) is fixed.
